# Generated by Django 3.1.6 on 2021-10-03 20:57

from django.db import migrations, models
import studymaterials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0019_auto_20210901_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('file', models.FileField(max_length=255, upload_to=studymaterials.models.get_study_material_file_path, verbose_name='Вложение')),
                ('training_groups', models.ManyToManyField(related_name='study_materials', to='programs.TrainingGroup', verbose_name='Учебная группа')),
            ],
            options={
                'verbose_name': 'Учебный материал',
                'verbose_name_plural': 'Учебные материалы',
            },
        ),
    ]
