# Generated by Django 3.1.6 on 2021-10-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymaterials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
