# Generated by Django 3.1.6 on 2021-02-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210202_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.CharField(blank=True, default='Россия', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=6, null=True),
        ),
    ]
