# Generated by Django 3.1.6 on 2021-02-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210215_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='link',
            field=models.URLField(blank=True, default='idab.mba', null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Полное имя'),
        ),
    ]
