# Generated by Django 3.1.6 on 2021-02-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210217_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='full_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное название должности'),
        ),
    ]
