# Generated by Django 3.1.6 on 2021-02-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_teacher_full_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='description',
            new_name='decription',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='full_position',
            new_name='full_teacher_position',
        ),
    ]
