# Generated by Django 3.1.6 on 2021-02-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210219_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='decription',
        ),
    ]
