# Generated by Django 3.1.6 on 2021-02-21 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210220_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='full_manager_position',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='manager_description',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='short_manager_position',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_teacher_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное название должности'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='short_teacher_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое название должности'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Mayfger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_manager_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое название должности')),
                ('full_manager_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное название должности')),
                ('manager_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('email2', models.EmailField(max_length=255, unique=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
