# Generated by Django 3.1.6 on 2021-02-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210221_0923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mayfger',
            new_name='Manager',
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Руководитель', 'verbose_name_plural': 'Руководство'},
        ),
    ]
