# Generated by Django 3.1.6 on 2021-02-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210221_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='manager_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='full_manager_position',
            new_name='full_position',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='short_manager_position',
            new_name='short_position',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='full_teacher_position',
            new_name='full_position',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='short_teacher_position',
            new_name='short_position',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_manager',
        ),
    ]
