# Generated by Django 3.1.6 on 2021-02-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210222_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='email2',
            field=models.EmailField(max_length=255),
        ),
    ]
