# Generated by Django 3.1.6 on 2021-02-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210222_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='on_site',
            field=models.BooleanField(default=False),
        ),
    ]
