# Generated by Django 3.1.6 on 2021-03-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_teacher_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
