# Generated by Django 3.1.6 on 2021-06-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210601_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='traning_group',
            new_name='training_group',
        ),
    ]
