# Generated by Django 3.1.6 on 2021-06-01 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_auto_20210402_1427'),
        ('users', '0028_auto_20210601_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='training_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='programs.traininggroup'),
        ),
    ]
