# Generated by Django 3.1.6 on 2021-08-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210601_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-id'], 'verbose_name': 'Слушатель', 'verbose_name_plural': 'Слушатели'},
        ),
    ]
