# Generated by Django 3.1.6 on 2021-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_auto_20210402_1427'),
        ('users', '0030_auto_20210815_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='training_group',
        ),
        migrations.AddField(
            model_name='student',
            name='training_group',
            field=models.ManyToManyField(null=True, related_name='students', to='programs.TrainingGroup'),
        ),
    ]
