# Generated by Django 3.1.6 on 2021-08-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_auto_20210816_1810'),
        ('users', '0031_auto_20210816_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='training_group',
        ),
        migrations.AddField(
            model_name='student',
            name='training_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='programs.traininggroup'),
        ),
    ]
