# Generated by Django 3.1.6 on 2021-11-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_traininggroup_slack_id'),
        ('users', '0033_auto_20210818_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='training_group',
            field=models.ManyToManyField(blank=True, related_name='students', to='programs.TrainingGroup'),
        ),
    ]
