# Generated by Django 3.1.6 on 2022-03-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_traininggroup_slack_id'),
        ('users', '0034_auto_20211111_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='training_group',
            field=models.ManyToManyField(blank=True, related_name='students', to='programs.TrainingGroup', verbose_name='Группа'),
        ),
    ]
