# Generated by Django 3.1.6 on 2021-03-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20210305_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['id'], 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
        migrations.AlterModelOptions(
            name='imageidab',
            options={'ordering': ['-id'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
