# Generated by Django 3.1.6 on 2021-02-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='siteblocks.contact', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='social',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='links', to='siteblocks.contact', verbose_name='Контакты'),
        ),
    ]
