# Generated by Django 3.1.6 on 2021-02-18 10:01

from django.db import migrations, models
import siteblocks.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0003_contact_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('avatar', models.ImageField(max_length=255, upload_to=siteblocks.models.rewiever_directory_path, verbose_name='Аватар')),
                ('body', models.TextField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
