# Generated by Django 3.1.6 on 2021-02-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
