# Generated by Django 3.1.6 on 2021-02-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0005_auto_20210218_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
