# Generated by Django 3.1.6 on 2021-02-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0010_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
    ]
