# Generated by Django 3.1.6 on 2021-03-17 10:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import siteblocks.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0012_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerption', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Цитата')),
                ('sub1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подпись1')),
                ('sub2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подпись2')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=siteblocks.models.about_directory_path, verbose_name='Титульное фото')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('order_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerption', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Цитата')),
                ('sub1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подпись1')),
                ('sub2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подпись2')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=siteblocks.models.about_directory_path, verbose_name='Титульное фото')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('order_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='siteblocks.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Подраздел',
                'verbose_name_plural': 'Подразделы',
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
