# Generated by Django 3.1.6 on 2021-02-16 16:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210216_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='decription',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='end',
            field=models.DateTimeField(verbose_name='Окончание события'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='start',
            field=models.DateTimeField(verbose_name='Начало события'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='decription',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
    ]
