# Generated by Django 3.1.6 on 2021-02-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='decription',
            new_name='description',
        ),
    ]
