# Generated by Django 3.1.6 on 2021-02-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210218_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='tmb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пиктограмма'),
        ),
        migrations.AddField(
            model_name='news',
            name='tmb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пиктограмма'),
        ),
    ]
