# Generated by Django 3.1.6 on 2021-02-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210218_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='tmb',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tmb',
        ),
    ]
