# Generated by Django 3.1.6 on 2021-03-02 11:16

import ckeditor_uploader.fields
from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210227_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('start', models.DateTimeField(verbose_name='Начало события')),
                ('end', models.DateTimeField(verbose_name='Окончание события')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('image', models.ImageField(max_length=255, upload_to=news.models.image_directory_path, verbose_name='Иллюстрация')),
                ('view', models.PositiveIntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'События',
                'verbose_name_plural': 'События',
                'ordering': ['-start'],
            },
        ),
    ]
