# Generated by Django 3.1.6 on 2021-03-07 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210302_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['startdate'], 'verbose_name': 'События', 'verbose_name_plural': 'События'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
        migrations.AddField(
            model_name='event',
            name='enddate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания события'),
        ),
        migrations.AddField(
            model_name='event',
            name='endtime',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания события'),
        ),
        migrations.AddField(
            model_name='event',
            name='startdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала события'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='starttime',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала события'),
            preserve_default=False,
        ),
    ]
