# Generated by Django 3.1.6 on 2021-11-11 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0033_auto_20210818_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_count', models.IntegerField(default=0)),
                ('attendace_count', models.IntegerField(default=0)),
                ('attendace_rating', models.IntegerField(default=0)),
                ('checkpoints_count', models.IntegerField(default=0)),
                ('completed_checkpoints', models.IntegerField(default=0)),
                ('completed_checkpoints_marks_avg', models.IntegerField(default=0)),
                ('checkpoints_rating', models.IntegerField(default=0)),
                ('tasks_count', models.IntegerField(default=0)),
                ('solutions_count', models.IntegerField(default=0)),
                ('solutions_mark_avg', models.IntegerField(default=0)),
                ('tasks_rating', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='users.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Райтинг',
                'verbose_name_plural': 'Райтинги',
            },
        ),
    ]
