# Generated by Django 3.1.6 on 2021-11-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='attendace_count',
            new_name='attendaces_count',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='attendace_rating',
            new_name='attendaces_rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='attendances_rating_prc',
            field=models.IntegerField(default=0),
        ),
    ]
