# Generated by Django 3.1.6 on 2021-11-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20211111_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='attendaces_count',
            new_name='attendances_count',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='attendaces_rating',
            new_name='attendances_rating',
        ),
    ]
