# Generated by Django 3.1.6 on 2021-11-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20211111_1228'),
        ('ratings', '0003_auto_20211111_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='users.student', verbose_name='Студент'),
        ),
    ]
