# Generated by Django 3.1.6 on 2022-03-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20211111_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='attendances_count',
            field=models.IntegerField(default=0, verbose_name='Посещенные занятия'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='attendances_rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг посещаемости'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='attendances_rating_prc',
            field=models.IntegerField(default=0, verbose_name='Посещаемость в %'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='checkpoints_count',
            field=models.IntegerField(default=0, verbose_name='Прошло контрольных точек (КТ)'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='checkpoints_rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг по КТ'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='completed_checkpoints',
            field=models.IntegerField(default=0, verbose_name='Сдано контрольных точек'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='completed_checkpoints_marks_avg',
            field=models.IntegerField(default=0, verbose_name='Средний бал за сданные КТ'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='schedule_count',
            field=models.IntegerField(default=0, verbose_name='Прошло занятий'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='solutions_count',
            field=models.IntegerField(default=0, verbose_name='Выполненных заданий'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='solutions_mark_avg',
            field=models.IntegerField(default=0, verbose_name='Средний бал за выполненные задания'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='tasks_count',
            field=models.IntegerField(default=0, verbose_name='Всего заданий'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='tasks_rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг по заданиям'),
        ),
    ]
