# Generated by Django 3.1.6 on 2021-09-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210922_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='traning_day',
            new_name='training_day',
        ),
    ]
