# Generated by Django 3.1.6 on 2021-09-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_auto_20210901_1321'),
        ('schedule', '0004_auto_20210922_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='training_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.traininggroup', verbose_name='Группа'),
        ),
    ]
