# Generated by Django 3.1.6 on 2021-09-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20210922_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start_time',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='training_day',
        ),
    ]
