# Generated by Django 3.1.6 on 2021-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
        ('users', '0033_auto_20210818_1502'),
        ('schedule', '0009_auto_20210923_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='visited_students',
            field=models.ManyToManyField(blank=True, null=True, through='attendances.Attendance', to='users.Student', verbose_name='Посетившие студенты'),
        ),
    ]
