# Generated by Django 3.1.6 on 2021-11-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20210818_1502'),
        ('attendances', '0001_initial'),
        ('checkpoints', '0006_auto_20211013_1904'),
        ('schedule', '0011_auto_20211013_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='checkpoints.checkpoint', verbose_name='Контрольная точка'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='visited_students',
            field=models.ManyToManyField(blank=True, through='attendances.Attendance', to='users.Student', verbose_name='Посетившие студенты'),
        ),
    ]
