# Generated by Django 3.1.6 on 2021-02-11 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_auto_20210211_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Наименование контрольной точки',
                'verbose_name_plural': 'Наименования контрольных точек',
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер подобной КТ для данного Курса')),
                ('in_table', models.BooleanField(default=False, verbose_name='Уже в расписании')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkpoints.checkpointsname', verbose_name='Название')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Контрольная точка',
                'verbose_name_plural': 'Контрольные точки',
                'unique_together': {('course', 'base', 'number')},
            },
        ),
    ]
