# Generated by Django 3.1.6 on 2021-02-11 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210209_1147'),
        ('checkpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Условия оценки')),
                ('value', models.PositiveIntegerField(verbose_name='Баллы')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='StudentCheckpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_passed', models.BooleanField(default=False)),
                ('checkpoint', models.ManyToManyField(to='checkpoints.Checkpoint', verbose_name='Контрольная точка')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkpoints.grade', verbose_name='Оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student', verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
