# Generated by Django 3.1.6 on 2021-02-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoints', '0002_grade_studentcheckpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcheckpoint',
            options={'verbose_name': 'КТ сеудента', 'verbose_name_plural': 'КТ студентов'},
        ),
        migrations.RemoveField(
            model_name='studentcheckpoint',
            name='checkpoint',
        ),
        migrations.AddField(
            model_name='studentcheckpoint',
            name='checkpoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='checkpoints.checkpoint', verbose_name='Контрольная точка'),
            preserve_default=False,
        ),
    ]
