# Generated by Django 3.1.6 on 2021-02-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoints', '0003_auto_20210211_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='studentcheckpoint',
            options={'verbose_name': 'КТ студента', 'verbose_name_plural': 'КТ студентов'},
        ),
    ]
