# Generated by Django 3.1.6 on 2021-10-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20210818_1502'),
        ('checkpoints', '0004_auto_20210214_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(verbose_name='Баллы')),
            ],
            options={
                'verbose_name': 'Оценка КТ студента',
                'verbose_name_plural': 'Оценки КТ студента',
            },
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.RemoveField(
            model_name='studentcheckpoint',
            name='checkpoint',
        ),
        migrations.RemoveField(
            model_name='studentcheckpoint',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentcheckpoint',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentcheckpoint',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='checkpoint',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='StudentCheckpoint',
        ),
        migrations.AddField(
            model_name='checkpointmark',
            name='checkpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chekpoint_marks', to='checkpoints.checkpoint', verbose_name='Контрольная точка'),
        ),
        migrations.AddField(
            model_name='checkpointmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chekpoint_marks', to='users.student', verbose_name='Студент'),
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='course',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='in_table',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='number',
        ),
    ]
