# Generated by Django 3.1.6 on 2021-10-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoints', '0005_auto_20211013_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkpoint',
            old_name='base',
            new_name='basic',
        ),
    ]
