# Generated by Django 3.1.6 on 2021-02-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20210209_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Контрольная точка',
                'verbose_name_plural': 'Контрольнае точки',
            },
        ),
        migrations.CreateModel(
            name='CoursesBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Блок дисциплин',
                'verbose_name_plural': 'Блоки дсциплин',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('hours', models.IntegerField(blank=True, null=True, verbose_name='Количество часов')),
                ('is_active', models.BooleanField(default=True)),
                ('blocks', models.ManyToManyField(to='courses.CoursesBlock', verbose_name='Блоки дсциплин')),
                ('checkpoints', models.ManyToManyField(to='courses.Checkpoint', verbose_name='Контрольные точки')),
                ('teachers', models.ManyToManyField(to='users.Teacher', verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
    ]
