# Generated by Django 3.1.6 on 2021-02-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210210_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpoint',
            options={'verbose_name': 'Контрольная точка', 'verbose_name_plural': 'Контрольные точки'},
        ),
        migrations.AlterModelOptions(
            name='checkpointsname',
            options={'verbose_name': 'Наименование контрольной точки', 'verbose_name_plural': 'Наименования контрольных точек'},
        ),
        migrations.RenameField(
            model_name='checkpoint',
            old_name='name',
            new_name='base',
        ),
    ]
