# Generated by Django 3.1.6 on 2021-02-10 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210210_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='checkpoints',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='Курс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterUniqueTogether(
            name='checkpoint',
            unique_together={('base', 'number', 'course')},
        ),
    ]
