# Generated by Django 3.1.6 on 2021-02-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210220_1428'),
        ('courses', '0007_auto_20210211_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='users.Teacher', verbose_name='Преподаватели'),
        ),
    ]
