# Generated by Django 3.1.6 on 2021-10-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211003_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='grade',
            new_name='mark',
        ),
    ]
