# Generated by Django 3.1.6 on 2021-10-06 11:02

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_auto_20210901_1321'),
        ('tasks', '0004_auto_20211003_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='training_group',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='programs.traininggroup', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=tasks.models.get_solution_file_path, verbose_name='Вложение'),
        ),
    ]
