# Generated by Django 3.1.6 on 2022-03-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
