# Generated by Django 3.1.6 on 2022-03-16 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_solution_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='mark',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Отметка'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='tasks.task', verbose_name='Задача'),
        ),
    ]
