# Generated by Django 3.1.6 on 2021-02-24 13:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0012_auto_20210222_1013'),
        ('news', '0009_auto_20210218_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправленно')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Доп иформация')),
            ],
            options={
                'verbose_name': 'Запись на обучение',
                'verbose_name_plural': 'Записи на обучение',
            },
        ),
        migrations.CreateModel(
            name='ProgramBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправленно')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('work_experience', models.PositiveIntegerField(verbose_name='Стаж')),
                ('education', models.CharField(max_length=255, verbose_name='Образование')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Запись на программу',
                'verbose_name_plural': 'Записи на программу',
            },
        ),
        migrations.CreateModel(
            name='PlanBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправленно')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Скачать план',
                'verbose_name_plural': 'Скачать планы',
            },
        ),
        migrations.CreateModel(
            name='EventBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправленно')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.announcement', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Запрос на участие',
                'verbose_name_plural': 'Запросы на участие',
            },
        ),
    ]
