# Generated by Django 3.1.6 on 2021-03-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_auto_20210302_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programbid',
            name='company',
        ),
        migrations.RemoveField(
            model_name='programbid',
            name='education',
        ),
        migrations.RemoveField(
            model_name='programbid',
            name='position',
        ),
        migrations.RemoveField(
            model_name='programbid',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programbid',
            name='work_experience',
        ),
    ]
