# Generated by Django 3.1.6 on 2021-03-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_program_slug'),
        ('bids', '0006_auto_20210319_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='programbid',
            name='company',
            field=models.CharField(default=1, max_length=255, verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programbid',
            name='education',
            field=models.CharField(default=1, max_length=255, verbose_name='Образование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programbid',
            name='position',
            field=models.CharField(default=1, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programbid',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='programs.program', verbose_name='Программа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programbid',
            name='work_experience',
            field=models.PositiveIntegerField(default=1, verbose_name='Стаж'),
            preserve_default=False,
        ),
    ]
