# Generated by Django 3.1.6 on 2021-02-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Программа')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGroupBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Учебная группа')),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало обучения')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Окончание обучения')),
                ('basic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='programs.traininggroupbasic')),
            ],
        ),
    ]
