# Generated by Django 3.1.6 on 2021-02-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='traininggroup',
            options={'ordering': ['-start_date'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='traininggroupbasic',
            options={'verbose_name': 'Группа(основа)', 'verbose_name_plural': 'Группы(основа)'},
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='basic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='programs.traininggroupbasic', verbose_name='Название группы'),
        ),
    ]
