# Generated by Django 3.1.6 on 2021-02-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20210215_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='programs.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Категория программ'),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_spring',
            field=models.DateField(blank=True, null=True, verbose_name='Весенний набор'),
        ),
    ]
