# Generated by Django 3.1.6 on 2021-02-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20210215_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='programs.category'),
        ),
    ]
