# Generated by Django 3.1.6 on 2021-02-18 11:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20210216_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='full_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='program',
            name='full_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание'),
        ),
    ]
