# Generated by Django 3.1.6 on 2021-02-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20210218_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория программ', 'verbose_name_plural': 'Категории программ'},
        ),
    ]
