# Generated by Django 3.1.6 on 2021-02-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20210218_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
    ]
