# Generated by Django 3.1.6 on 2021-02-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_program_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория программ', 'verbose_name_plural': 'Категории программ'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['id'], 'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
    ]
