# Generated by Django 3.1.6 on 2021-02-22 10:13

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_auto_20210218_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=programs.models.image_directory_path, verbose_name='Иллюстрация'),
        ),
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=programs.models.image_directory_path, verbose_name='Иллюстрация'),
        ),
    ]
