# Generated by Django 3.1.6 on 2021-02-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_auto_20210222_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='program',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
