# Generated by Django 3.1.6 on 2021-03-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_auto_20210225_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
