# Generated by Django 3.1.6 on 2021-08-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_auto_20210402_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininggroup',
            options={'ordering': ['-id'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
