# Generated by Django 3.1.6 on 2021-09-01 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_auto_20210816_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininggroupbasic',
            name='program',
        ),
        migrations.AddField(
            model_name='traininggroupbasic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_groups', to='programs.category'),
        ),
    ]
